config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'fish/index'
      post 'fish/create'
      delete 'fish/:id', to: 'fish#destroy'
    end
  end

  root 'fish#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fish.rb
class Fish < ApplicationRecord
end

app/controllers/api/v1/fish_controller.rb
class Api::V1::FishController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]

  # GET /fish
  # GET /fish/.json

  def index 
    @fish = Fish.all.order(common_name: :asc)
    render json: @fish
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
    if @fish
      render json: @fish
    else
      render json: @fish.errors
    end
  end

  # GET /fish/new
  def new 
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(fish_params)

    if @fish.save
      render json: @fish      
    else  
      render json: @fish.errors
    end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
  end
  
  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy 
    @fish.destroy

    render json: { notice: 'Fish was successfully removed.'}
  end

  private 
    # Use callbacks to share common setup or constraints  between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fish_params
      params.permit(:common_name, :scientific_name, :ph, :quantity)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  
  def index
  end

end

app/helpers/api/v1/fish_helper.rb
module Api::V1::FishHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= form_with(model: fish) do |form| %>
  <% if fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
        <% fish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :common_name %>
    <%= form.text_field :common_name %>
  </div>

  <div class="field">
    <%= form.label :scientific_name %>
    <%= form.text_field :scientific_name %>
  </div>

  <div class="field">
    <%= form.label :ph %>
    <%= form.text_field :ph %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Editing Fish</h1>

<%= render 'form', fish: @fish %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/new.html.erb
<h1>New Fish</h1>

<%= render 'form', fish: @fish %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @fish.common_name %>
</p>

<p>
  <strong>Scientific name:</strong>
  <%= @fish.scientific_name %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @fish.ph %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @fish.quantity %>
</p>

<%= link_to 'Edit', edit_fish_path(@fish) %> |
<%= link_to 'Back', fish_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudRailsReact</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>